# Generated by Django 5.1.4 on 2024-12-13 21:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_folder_share_with_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='share_link',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='folder',
            name='share_link_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
