# Generated by Django 5.1.4 on 2024-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='otp_used',
            field=models.BooleanField(default=False),
        ),
    ]
