# Generated by Django 5.1.4 on 2024-12-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_otp_code_account_otp_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='otp_used',
        ),
    ]
