# Generated by Django 5.1.4 on 2024-12-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_folder_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='share_with_all',
            field=models.BooleanField(default=True),
        ),
    ]
