# Generated by Django 5.1.4 on 2024-12-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_alter_folder_share_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='share_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
