# Generated by Django 5.1.4 on 2024-12-14 07:44

import storage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_folder_share_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='share_link',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='share_link_expiry',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_expiry',
            field=models.DateTimeField(blank=True, default=storage.models.default_folder_expiry, null=True),
        ),
    ]
