# Generated by Django 5.1.4 on 2024-12-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_remove_folder_share_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_encrypted',
            field=models.BooleanField(default=True),
        ),
    ]
